{% set name = "pypar" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pypar-{{ version }}.tar.gz
  sha256: e69a3c3e974451ae29bf0889fb22b5b93ff17209f035dbdb63373a89f495e971

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy

test:
  imports:
    - pypar
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/maxrmorrison/pypar
  summary: Python phoneme alignment representation
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
